x-common-env: &common_env
  PUID: ${PUID}
  PGID: ${PGID}
  TZ: ${TZ}

x-common-service: &common_service
  networks:
    - homelab_network
  restart: unless-stopped

name: homelab-media
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    <<: *common_service
    environment:
      <<: *common_env
    ports:
      - ${BAZARR_PORT}:6767
    volumes:
      - ${CONFIG_ROOT}/bazarr/config:/config
      - ${NAS}:${NAS}
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "512M"

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    <<: *common_service
    environment:
      <<: *common_env
      AUTO_UPDATE: true
      RUN_OPTS:
    ports:
      - ${JACKETT_PORT}:9117
    volumes:
      - ${CONFIG_ROOT}/jackett/config:/config
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "256M"

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    privileged: true
    <<: *common_service
    environment:
      <<: *common_env
    ports:
      - ${JELLYFIN_PORT}:8096
    volumes:
      - ${CONFIG_ROOT}/jellyfin/config:/config
      - ${NAS}:${NAS}
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    group_add:
      - video
      - "107"
    deploy:
      resources:
        limits:
          cpus: "6.0"
          memory: "4G"

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    <<: *common_service
    environment:
      <<: *common_env
      LOG_LEVEL: debug
    ports:
      - ${JELLYSEERR_PORT}:5055
    volumes:
      - ${CONFIG_ROOT}/jellyseerr/config:/app/config
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"

  komga:
    image: gotson/komga
    <<: *common_service
    environment:
      <<: *common_env
      JAVA_TOOL_OPTIONS: -Xmx1g
    ports:
      - ${KOMGA_PORT}:25600
    volumes:
      - ${CONFIG_ROOT}/komga/config:/config
      - ${CONFIG_ROOT}/komga/data:/data
      - ${NAS}:${NAS}
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "2G"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    <<: *common_service
    environment:
      <<: *common_env
      WEBUI_PORT: ${QBITTORRENT_PORT_UI}
      TORRENTING_PORT: ${QBITTORRENT_PORT_TRAFFIC}
    ports:
      - ${QBITTORRENT_PORT_UI}:8080
      - ${QBITTORRENT_PORT_TRAFFIC}:6881
      - ${QBITTORRENT_PORT_TRAFFIC}:6881/udp
    volumes:
      - ${CONFIG_ROOT}/qbittorrent/config:/config
      - ${APPS}:${APPS}
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "1G"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    <<: *common_service
    environment:
      <<: *common_env
    ports:
      - ${RADARR_PORT}:7878
    volumes:
      - ${CONFIG_ROOT}/radarr/config:/config
      - ${NAS}:${NAS}
      - ${APPS}:${APPS}
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "2G"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    <<: *common_service
    environment:
      <<: *common_env
    ports:
      - ${SONARR_PORT}:8989
    volumes:
      - ${CONFIG_ROOT}/sonarr/config:/config
      - ${NAS}:${NAS}
      - ${APPS}:${APPS}
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "2G"

networks:
  homelab_network:
    external: true