title: ${SERVER_HOSTNAME} Homepage
theme: dark
color: slate
useEqualHeights: false
headerStyle: boxedWidgets
disableCollapse: false
hideVersion: true
maxGroupColumns: 5

background:
    image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    blur: xs
    saturate: 50
    brightness: 50

layout:
    Applications:
        style: column
        rows: 2
    Logging:
        style: column
        rows: 3
    Media:
        style: column
        rows: 8
    Networking:
        style: column
        rows: 4
    System:
        style: column
        rows: 2
