title: TrueNAS Home
theme: dark
color: slate
useEqualHeights: false
headerStyle: boxedWidgets
disableCollapse: false
hideVersion: true

layout:
    Services:
        style: row
        columns: 3
    Admin:
        style: row
        columns: 2
        System:
            style: row
            columns: 2
        Media:
            style: row
            columns: 2